services:
  pidea-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: fr4iser/pidea:db
    container_name: pidea-db
    ports:
      - "5452:5432"
    volumes:
      - pidea-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  pidea-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    image: fr4iser/pidea:backend
    container_name: pidea-backend
    ports:
      - "8090:8000"
    depends_on:
      pidea-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - pidea-backend_logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  pidea-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    image: fr4iser/pidea:frontend
    container_name: pidea-frontend
    ports:
      - "4040:4000"
    depends_on:
      - pidea-backend
    env_file:
      - .env
    volumes:
      - pidea-frontend_logs:/var/log/nginx
    restart: unless-stopped

volumes:
  pidea-db-data:
    driver: local
  pidea-backend_logs:
    driver: local
  pidea-frontend_logs:
    driver: local
