services:
  pidea-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: fr4iser/pidea:db
    container_name: pidea-db
    ports:
      - "5452:5432"
    volumes:
      - pidea-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pidea
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pidea"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s

  pidea-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: fr4iser/pidea:backend
    container_name: pidea-backend
    ports:
      - "8090:3000"
    depends_on:
      pidea-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: pidea-db
      DB_PORT: 5432
      DB_NAME: pidea
      DB_USER: postgres
      DB_PASSWORD: postgres
    env_file:
      - .env
    volumes:
      - pidea-backend_logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  pidea-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: fr4iser/pidea:frontend
    container_name: pidea-frontend
    ports:
      - "80:80"
    depends_on:
      - pidea-backend
    env_file:
      - .env
    volumes:
      - pidea-frontend_logs:/var/log/nginx
    restart: unless-stopped

volumes:
  pidea-db-data:
    driver: local
  pidea-backend_logs:
    driver: local
  pidea-frontend_logs:
    driver: local
