services:
  cursor-to-bolt-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: fr4iser/cursor-to-bolt:db
    container_name: cursor-to-bolt-db
    ports:
      - "5452:5432"
    volumes:
      - cursor-to-bolt-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  cursor-to-bolt-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    image: fr4iser/cursor-to-bolt:backend
    container_name: cursor-to-bolt-backend
    ports:
      - "8090:8000"
    depends_on:
      cursor-to-bolt-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - cursor-to-bolt-backend_logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  cursor-to-bolt-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    image: fr4iser/cursor-to-bolt:frontend
    container_name: cursor-to-bolt-frontend
    ports:
      - "4040:4000"
    depends_on:
      - cursor-to-bolt-backend
    env_file:
      - .env
    volumes:
      - cursor-to-bolt-frontend_logs:/var/log/nginx
    restart: unless-stopped

volumes:
  cursor-to-bolt-db-data:
    driver: local
  cursor-to-bolt-backend_logs:
    driver: local
  cursor-to-bolt-frontend_logs:
    driver: local
